package dev.tanaka.wynnaibridge.config;

import net.fabricmc.loader.api.FabricLoader;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.SecureRandom;
import java.util.Base64;
import java.util.Properties;
import dev.tanaka.wynnaibridge.ui.UiActionGate;

public final class BridgeConfig {
    private final int port;
    private final String tailscaleHost;
    private final boolean allowActions;
    private final String token;
    private final boolean tokenAutoGenerated;
    private volatile boolean allowUiActions;
    private volatile int uiActionsMaxArmSeconds;
    private final boolean knowledgeEnabled;
    private final boolean wikiEnabled;
    private final int knowledgeRefreshMinutes;
    private final int knowledgeHttpTimeoutSeconds;

    public BridgeConfig(int port, String tailscaleHost, boolean allowActions, String token,
                        boolean tokenAutoGenerated, boolean allowUiActions, int uiActionsMaxArmSeconds,
                        boolean knowledgeEnabled, boolean wikiEnabled, int knowledgeRefreshMinutes,
                        int knowledgeHttpTimeoutSeconds) {
        this.port = port;
        this.tailscaleHost = tailscaleHost;
        this.allowActions = allowActions;
        this.token = token;
        this.tokenAutoGenerated = tokenAutoGenerated;
        this.allowUiActions = allowUiActions;
        this.uiActionsMaxArmSeconds = clampMaxArmSeconds(uiActionsMaxArmSeconds);
        this.knowledgeEnabled = knowledgeEnabled;
        this.wikiEnabled = wikiEnabled;
        this.knowledgeRefreshMinutes = knowledgeRefreshMinutes;
        this.knowledgeHttpTimeoutSeconds = knowledgeHttpTimeoutSeconds;
    }

    public int port() { return port; }
    public String tailscaleHost() { return tailscaleHost; }
    public boolean allowActions() { return allowActions; }
    public String token() { return token; }
    public boolean tokenAutoGenerated() { return tokenAutoGenerated; }
    public boolean allowUiActions() { return allowUiActions; }
    public int uiActionsMaxArmSeconds() { return uiActionsMaxArmSeconds; }
    public boolean knowledgeEnabled() { return knowledgeEnabled; }
    public boolean wikiEnabled() { return wikiEnabled; }
    public int knowledgeRefreshMinutes() { return knowledgeRefreshMinutes; }
    public int knowledgeHttpTimeoutSeconds() { return knowledgeHttpTimeoutSeconds; }
    private static final int DEFAULT_PORT = 8765;
    private static final SecureRandom SECURE_RANDOM = new SecureRandom();

    public static BridgeConfig load() {
        Path path = configPath();
        Properties p = new Properties();
        boolean dirty = false;

        try {
            if (Files.exists(path)) {
                try (InputStream in = Files.newInputStream(path)) {
                    p.load(in);
                }
            } else {
                dirty = true;
            }
        } catch (IOException ignored) {
            // Keep safe defaults if the file cannot be read.
            dirty = true;
        }

        dirty |= putDefault(p, "port", Integer.toString(DEFAULT_PORT));
        dirty |= putDefault(p, "tailscaleHost", "");
        dirty |= putDefault(p, "allowActions", "false");
        dirty |= putDefault(p, "token", "");
        dirty |= putDefault(p, "allowUiActions", "false");
        dirty |= putDefault(p, "uiActions.maxArmSeconds", "300");
        dirty |= putDefault(p, "knowledge.enabled", "true");
        dirty |= putDefault(p, "knowledge.wikiEnabled", "true");
        dirty |= putDefault(p, "knowledge.refreshMinutes", "60");
        dirty |= putDefault(p, "knowledge.httpTimeoutSeconds", "12");
        dirty |= putDefault(p, "deepl.authKey", "");

        int port = parseInt(p, "port", DEFAULT_PORT, 1024, 65535);
        String tailscaleHost = p.getProperty("tailscaleHost", "").trim();
        boolean allowActions = Boolean.parseBoolean(p.getProperty("allowActions", "false").trim());
        String token = p.getProperty("token", "").trim();
        boolean tokenAutoGenerated = false;
        boolean allowUiActions = Boolean.parseBoolean(p.getProperty("allowUiActions", "false").trim());
        int uiActionsMaxArmSeconds = parseInt(p, "uiActions.maxArmSeconds", 300, 30, 300);

        // Fail closed: actions may never run without an authentication token.
        if (allowActions && token.isEmpty()) {
            token = generateToken();
            p.setProperty("token", token);
            tokenAutoGenerated = true;
            dirty = true;
        }

        boolean knowledgeEnabled = Boolean.parseBoolean(p.getProperty("knowledge.enabled", "true").trim());
        boolean wikiEnabled = Boolean.parseBoolean(p.getProperty("knowledge.wikiEnabled", "true").trim());
        int knowledgeRefreshMinutes = parseInt(p, "knowledge.refreshMinutes", 60, 10, 1440);
        int knowledgeHttpTimeoutSeconds = parseInt(p, "knowledge.httpTimeoutSeconds", 12, 3, 60);

        if (dirty) {
            try {
                Files.createDirectories(path.getParent());
                try (OutputStream out = Files.newOutputStream(path)) {
                    p.store(out,
                        "Wynn AI Bridge - localhost only. Actions require a bearer token. " +
                        "Knowledge lookups use the official Wynncraft API/wiki when enabled.");
                }
            } catch (IOException e) {
                // If we could not persist a generated token, disable actions rather than
                // leaving a privileged endpoint usable with an unknown/ephemeral secret.
                if (tokenAutoGenerated) {
                    allowActions = false;
                    token = "";
                    tokenAutoGenerated = false;
                }
            }
        }

        return new BridgeConfig(
            port,
            tailscaleHost,
            allowActions,
            token,
            tokenAutoGenerated,
            allowUiActions,
            uiActionsMaxArmSeconds,
            knowledgeEnabled,
            wikiEnabled,
            knowledgeRefreshMinutes,
            knowledgeHttpTimeoutSeconds
        );
    }

    private static boolean putDefault(Properties p, String key, String value) {
        if (p.containsKey(key)) return false;
        p.setProperty(key, value);
        return true;
    }

    private static int parseInt(Properties p, String key, int fallback, int min, int max) {
        try {
            int value = Integer.parseInt(p.getProperty(key, Integer.toString(fallback)).trim());
            int clamped = Math.max(min, Math.min(max, value));
            if (clamped != value) p.setProperty(key, Integer.toString(clamped));
            return clamped;
        } catch (NumberFormatException e) {
            p.setProperty(key, Integer.toString(fallback));
            return fallback;
        }
    }

    public static int clampMaxArmSeconds(int seconds) {
        return Math.max(30, Math.min(seconds, 300));
    }

    /** Persist and apply only the safe UI-action settings; false always clears the process-local arm. */
    public synchronized void updateUiSettings(boolean enabled, int maxArmSeconds) throws IOException {
        updateUiSettings(configPath(), enabled, maxArmSeconds);
    }

    public synchronized void updateUiSettings(Path path, boolean enabled, int maxArmSeconds) throws IOException {
        int clamped = clampMaxArmSeconds(maxArmSeconds);
        Properties properties = new Properties();
        if (Files.isRegularFile(path)) {
            try (InputStream in = Files.newInputStream(path)) { properties.load(in); }
        }
        properties.setProperty("allowUiActions", Boolean.toString(enabled));
        properties.setProperty("uiActions.maxArmSeconds", Integer.toString(clamped));
        Files.createDirectories(path.getParent());
        try (OutputStream out = Files.newOutputStream(path)) {
            properties.store(out, "Wynn AI Bridge - UI action settings");
        }
        if (!enabled) UiActionGate.INSTANCE.disarm();
        this.allowUiActions = enabled;
        this.uiActionsMaxArmSeconds = clamped;
    }

    private static Path configPath() {
        return FabricLoader.getInstance().getConfigDir().resolve("wynn-ai-bridge.properties");
    }

    private static String generateToken() {
        byte[] bytes = new byte[32];
        SECURE_RANDOM.nextBytes(bytes);
        return Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);
    }
}
