package dev.tanaka.wynnaibridge.config;

import net.fabricmc.loader.api.FabricLoader;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.SecureRandom;
import java.util.Base64;
import java.util.Properties;

public record BridgeConfig(
    int port,
    String tailscaleHost,
    boolean allowActions,
    String token,
    boolean tokenAutoGenerated,
    boolean allowUiActions,
    int uiActionsMaxArmSeconds,
    boolean knowledgeEnabled,
    boolean wikiEnabled,
    int knowledgeRefreshMinutes,
    int knowledgeHttpTimeoutSeconds
) {
    private static final int DEFAULT_PORT = 8765;
    private static final SecureRandom SECURE_RANDOM = new SecureRandom();

    public static BridgeConfig load() {
        Path path = FabricLoader.getInstance().getConfigDir().resolve("wynn-ai-bridge.properties");
        Properties p = new Properties();
        boolean dirty = false;

        try {
            if (Files.exists(path)) {
                try (InputStream in = Files.newInputStream(path)) {
                    p.load(in);
                }
            } else {
                dirty = true;
            }
        } catch (IOException ignored) {
            // Keep safe defaults if the file cannot be read.
            dirty = true;
        }

        dirty |= putDefault(p, "port", Integer.toString(DEFAULT_PORT));
        dirty |= putDefault(p, "tailscaleHost", "");
        dirty |= putDefault(p, "allowActions", "false");
        dirty |= putDefault(p, "token", "");
        dirty |= putDefault(p, "allowUiActions", "false");
        dirty |= putDefault(p, "uiActions.maxArmSeconds", "300");
        dirty |= putDefault(p, "knowledge.enabled", "true");
        dirty |= putDefault(p, "knowledge.wikiEnabled", "true");
        dirty |= putDefault(p, "knowledge.refreshMinutes", "60");
        dirty |= putDefault(p, "knowledge.httpTimeoutSeconds", "12");
        dirty |= putDefault(p, "deepl.authKey", "");

        int port = parseInt(p, "port", DEFAULT_PORT, 1024, 65535);
        String tailscaleHost = p.getProperty("tailscaleHost", "").trim();
        boolean allowActions = Boolean.parseBoolean(p.getProperty("allowActions", "false").trim());
        String token = p.getProperty("token", "").trim();
        boolean tokenAutoGenerated = false;
        boolean allowUiActions = Boolean.parseBoolean(p.getProperty("allowUiActions", "false").trim());
        int uiActionsMaxArmSeconds = parseInt(p, "uiActions.maxArmSeconds", 300, 30, 300);

        // Fail closed: actions may never run without an authentication token.
        if (allowActions && token.isEmpty()) {
            token = generateToken();
            p.setProperty("token", token);
            tokenAutoGenerated = true;
            dirty = true;
        }

        boolean knowledgeEnabled = Boolean.parseBoolean(p.getProperty("knowledge.enabled", "true").trim());
        boolean wikiEnabled = Boolean.parseBoolean(p.getProperty("knowledge.wikiEnabled", "true").trim());
        int knowledgeRefreshMinutes = parseInt(p, "knowledge.refreshMinutes", 60, 10, 1440);
        int knowledgeHttpTimeoutSeconds = parseInt(p, "knowledge.httpTimeoutSeconds", 12, 3, 60);

        if (dirty) {
            try {
                Files.createDirectories(path.getParent());
                try (OutputStream out = Files.newOutputStream(path)) {
                    p.store(out,
                        "Wynn AI Bridge - localhost only. Actions require a bearer token. " +
                        "Knowledge lookups use the official Wynncraft API/wiki when enabled.");
                }
            } catch (IOException e) {
                // If we could not persist a generated token, disable actions rather than
                // leaving a privileged endpoint usable with an unknown/ephemeral secret.
                if (tokenAutoGenerated) {
                    allowActions = false;
                    token = "";
                    tokenAutoGenerated = false;
                }
            }
        }

        return new BridgeConfig(
            port,
            tailscaleHost,
            allowActions,
            token,
            tokenAutoGenerated,
            allowUiActions,
            uiActionsMaxArmSeconds,
            knowledgeEnabled,
            wikiEnabled,
            knowledgeRefreshMinutes,
            knowledgeHttpTimeoutSeconds
        );
    }

    private static boolean putDefault(Properties p, String key, String value) {
        if (p.containsKey(key)) return false;
        p.setProperty(key, value);
        return true;
    }

    private static int parseInt(Properties p, String key, int fallback, int min, int max) {
        try {
            int value = Integer.parseInt(p.getProperty(key, Integer.toString(fallback)).trim());
            int clamped = Math.max(min, Math.min(max, value));
            if (clamped != value) p.setProperty(key, Integer.toString(clamped));
            return clamped;
        } catch (NumberFormatException e) {
            p.setProperty(key, Integer.toString(fallback));
            return fallback;
        }
    }

    private static String generateToken() {
        byte[] bytes = new byte[32];
        SECURE_RANDOM.nextBytes(bytes);
        return Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);
    }
}
